import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import Rooms from '@/components/Rooms'
import FAQ from '@/components/FAQ'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/nodge_logo.png" />
      </Head>
      <Header />
      <Hero />
      <Rooms />
      <FAQ />
      <Footer />
    </>
  )
}
